// Generated by https://quicktype.io
import { Establecimiento } from 'core/establecimiento';
import { Role } from 'core/role';
import { User } from 'core/user';
export interface ProfileResponse {
  user: {
    data: User;
  };
  establecimiento: {
    data: Establecimiento;
  };
  roles: {
    data: Role[];
  };
}
