// Generated by https://quicktype.io

export interface Establecimiento {
  id: number;
  nombre: string;
  codigo: number;
  direccion: string;
  telefono: number;
  ris: string;
  real_id: number;
  has_lab: boolean;
}
