// Generated by https://quicktype.io

export interface Establecimiento {
  id: string;
  nombre: string;
  codigo: string;
  direccion: string;
  telefono: number;
  ris: string;
  real_id: number;
}
