// Generated by https://quicktype.io

export interface Privilegio {
  object: string;
  id: number;
  nombre: string;
  descripcion?: string;
  ruta?: string;
  icono: string;
  parent_id?: number;
  checked?: boolean;
}
