/* eslint-disable @typescript-eslint/no-explicit-any */
import { AxiosResponse } from 'axios';
// Generated by https://quicktype.io

export interface Meta {
  include: any[];
  custom: any[];
  pagination: ServerPagination;
}

export interface ServerPagination {
  total: number;
  count: number;
  per_page: number;
  current_page: number;
  total_pages: number;
  links: Links;
}

export interface Links {
  previous: string;
  next: string;
}

export interface Query {
  page?: number;
  limit?: number;
  orderBy?: string;
  sortedBy?: 'asc' | 'desc';
  search?: string;
  searchJoin?: string;
  include?: string;
}
export interface ApiatoResponse<T> {
  data: T;
  meta: Meta;
}

interface ErrorData<T = any> {
  message: string;
  errors: {
    [key in keyof T]: string[];
  };
  exception?: string;
  file?: string;
  line?: number;
}

export type ApiatoError<T = any> = AxiosResponse<ErrorData<T>>;
