// Generated by https://quicktype.io

export interface PersonaRequest {
  nombres: string;
  apellido_paterno: string;
  apellido_materno: string;
  numero_documento: number;
  fecha_nacimiento: string | Date;
  edad: number;
  sexo: string;
  direccion: string;
  telefono: number;
  historia_clinica: number;
  tipo_documento_id: number;
  tipo_persona_id: number;
}
