// Generated by https://quicktype.io

export interface Reniec {
  id: number;
  dni: string;
  digito_verificacion: string;
  apellido_paterno: string;
  apellido_materno: string;
  apelido_casado: string;
  nombres: string;
  codigo_ubigeo_domicilio: string;
  codigo_ubigeo_pais: string;
  codigo_ubigeo_departamento: string;
  codigo_ubigeo_provincia: string;
  codigo_ubigeo_distrito: string;
  codigo_ubigeo_localidad: string;
  continente_domicilio: string;
  pais_domicilio: string;
  departamento_domicilio: string;
  provincia_domicilio: string;
  distrito_domicilio: string;
  localidad_domicilio: string;
  estado_civil: string;
  codigo_grado_instruccion: string;
  sexo: string;
  codigo_ubigeo_departamento_nacimiento: string;
  codigo_ubigeo_provincia_nacimiento: string;
  codigo_ubigeo_distrito_nacimiento: string;
  departamento_nacimiento: string;
  provincia_nacimiento: string;
  distrito_nacimiento: string;
  fecha_nacimiento: string;
  nombres_padre: string;
  nombres_madre: string;
  fecha_inscripcion: string;
  fecha_expedicion: string;
  restricciones: string;
  prefijo_direccion: string;
  direccion: string;
  numero_direccion: string;
  manzana: string;
  lote: string;
}
