// Generated by https://quicktype.io

import { Signo } from 'core/signo';

export interface Triaje {
  object: string;
  id: number;
  fecha_registro: string | Date;
  paciente_id: number;
  pivot: { signo_id: number; valor: number; triaje_id: number }[];
  signos: {
    data: Signo[];
  };
  // fecha_registro: string | Date;
}
