// Generated by https://quicktype.io

import { Item } from 'core/item';
import { Respuesta } from 'core/respuesta';
import { Unidad } from 'core/unidad';
import { Categoria } from './Categoria';

export interface Examen {
  object: string;
  id: number;
  nombre: string;
  precio: number;
  categoria_id: number;
  categoria: {
    data: Categoria;
  };
  unidads: {
    data: Unidad[];
  };
  pivot: {
    examen_id: number;
    unidad_id: number;
    minimo: number;
    maximo: number;
  }[];
  items: {
    data: Item[];
  };
  respuestas: {
    data: Respuesta[];
  };
  ordens_count?: number;
  tipo: string;
}
