// Generated by https://quicktype.io

import { Categoria } from './Categoria';

export interface Examen {
  object: string;
  id: number;
  nombre: string;
  unidad: string;
  precio: number;
  categoria_id: number;
  categoria: {
    data: Categoria;
  };
}
