// Generated by https://quicktype.io

import { Diagnostico } from 'core/diagnostico';

export interface Persona {
  id: string;
  nombres: string;
  apellido_paterno: string;
  apellido_materno: string;
  numero_documento: number;
  fecha_nacimiento: string | Date;
  edad: number;
  sexo: string;
  direccion: string;
  telefono: number;
  historia_clinica: number;
  tipo_documento: string;
  tipo_persona: string;
  real_id: number;
  diagnosticos: {
    data: Diagnostico[];
  };
}
