export const enum QueryTypes {
  ROLES_ALL = 'roles-all',
  CHECK_PHP_REQUIREMENTS = 'check-php-requirements',
  CHECK_FOLDER_PERMISSIONS = 'check-folder-permissions',
  CHECK_STEP = 'check-step',
  PERIODS_ALL = 'periods-all',
  GOL_ALL = 'gol-all',
  ACADEMIC_ENTITY_ALL = 'academic-entity-all',
  TIPO_DOCUMENTO_ALL = 'tipo-documento-all',
  PERSONA_ALL = 'personas',
  FINANCIAMIENTO_ALL = 'financiamiento',
  ENFERMEDAD_ALL = 'enfermedades',
  DIAGNOSTICO_ALL = 'diagnosticos',
  MEDICAMENTO_ALL = 'medicamentos',
  COMPLICACION_ALL = 'complicaciones',
}
